# Generated by Django 4.1.5 on 2023-01-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snm', models.CharField(max_length=30)),
                ('sid', models.IntegerField()),
                ('sads', models.CharField(max_length=60)),
                ('semail', models.EmailField(max_length=254)),
                ('sph', models.IntegerField()),
                ('spwd', models.CharField(max_length=20)),
            ],
        ),
    ]
