# Generated by Django 4.1.5 on 2023-02-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_pdtupldmodel_pdtimg_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnm', models.CharField(max_length=20)),
                ('prc', models.IntegerField()),
                ('pdtimg', models.ImageField(upload_to='')),
                ('dsc', models.CharField(max_length=40)),
            ],
        ),
    ]
