# Generated by Django 4.1.5 on 2023-02-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_buymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardpaydetailsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnum', models.CharField(max_length=30)),
                ('cardexpdate', models.CharField(max_length=30)),
                ('securitycode', models.CharField(max_length=40)),
            ],
        ),
    ]
