# Generated by Django 4.1.5 on 2023-02-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_pdtupldmodel_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
